### ISSUE TITLE
Update inclusive DY mll>50 x-secs

### ISSUE THREAD

**Issue by danbarto** [HephyAnalysisSW/Samples#17]
We should update the DY x-sec for mll>50 GeV to the newest calculations, the new value is 2075.14*3 [1]. I'm in the middle of a production of DY samples right now, but I'd update them beginning of next week. Is that fine for everybody? @mzarucki @llechner 

[1] https://twiki.cern.ch/twiki/bin/view/CMS/SummaryTable1G25ns#DY_Z

**Comment by mzarucki** [comment]
Yes, that's fine with me!

Can we update it in all definition files together with the minor xsec changes here as well https://github.com/HephyAnalysisSW/Samples/pull/16 ?

**Comment by danbarto** [comment]
Good point. Yes, I'll take care of that as well.

**Comment by mzarucki** [comment]
Hey,

So I made the discussed changes in the following PR: https://github.com/HephyAnalysisSW/Samples/pull/19

Please take a moment to review and ensure that everything is as expected.

Cheers,
Mateusz

**Comment by mzarucki** [comment]
Updated remaining xsec for Autumn18 in this commit: https://github.com/HephyAnalysisSW/Samples/commit/915f25cc6032c2b9fd9fb4d812d471f5a1177cc4
