### ISSUE TITLE
Align HT-binned DY cross-sections

### ISSUE THREAD

**Issue by mzarucki** [HephyAnalysisSW/Samples#20]
HT-binned DY cross-sections do not match between central and private files. Here is the output of the simple script which compares the cross-sections in all the sample definition files, [xsecDifferences.txt](https://github.com/HephyAnalysisSW/Samples/files/3143201/xsecDifferences.txt): 

* DYJetsToLL_M50_HT70to100 xsec 180.195 from Autumn18_private_legacy_v1 different to xsec 209.592 from Summer16_05Feb2018
* DYJetsToLL_M50_HT70to100 xsec 181.671 from Fall17_private_legacy_v1 different to xsec 209.592 from Summer16_05Feb2018
* DYJetsToLL_M50_HT100to200 xsec 196.923 from Autumn18_private_legacy_v1 different to xsec 181.302 from Summer16_05Feb2018
* DYJetsToLL_M50_HT100to200 xsec 198.153 from Fall17_private_legacy_v1 different to xsec 181.302 from Summer16_05Feb2018
* DYJetsToLL_M50_HT200to400 xsec 60.5406 from Autumn18_private_legacy_v1 different to xsec 50.4177 from Summer16_05Feb2018
* DYJetsToLL_M50_HT200to400 xsec 59.7534 from Fall17_private_legacy_v1 different to xsec 50.4177 from Summer16_05Feb2018
* DYJetsToLL_M50_HT200to400_ext xsec 59.7534 from Fall17_private_legacy_v1 different to xsec 50.4177 from Summer16_05Feb2018
* DYJetsToLL_M50_HT400to600 xsec 8.60508 from Autumn18_private_legacy_v1 different to xsec 6.98394 from Summer16_05Feb2018
* DYJetsToLL_M50_HT400to600 xsec 8.58417 from Fall17_private_legacy_v1 different to xsec 6.98394 from Summer16_05Feb2018
* DYJetsToLL_M50_HT400to600_ext xsec 8.60508 from Autumn18_private_legacy_v1 different to xsec 6.98394 from Summer16_05Feb2018
* DYJetsToLL_M50_HT400to600_ext xsec 8.58417 from Fall17_private_legacy_v1 different to xsec 6.98394 from Summer16_05Feb2018
* DYJetsToLL_M50_HT600to800 xsec 2.15742 from Autumn18_private_legacy_v1 different to xsec 1.68141 from Summer16_05Feb2018
* DYJetsToLL_M50_HT600to800 xsec 2.13774 from Fall17_private_legacy_v1 different to xsec 1.68141 from Summer16_05Feb2018
* DYJetsToLL_M50_HT800to1200 xsec 1.072314 from Autumn18_private_legacy_v1 different to xsec 0.775392 from Summer16_05Feb2018
* DYJetsToLL_M50_HT800to1200 xsec 0.993471 from Fall17_private_legacy_v1 different to xsec 0.775392 from Summer16_05Feb2018
* DYJetsToLL_M50_HT1200to2500 xsec 0.238374 from Autumn18_private_legacy_v1 different to xsec 0.186222 from Summer16_05Feb2018
* DYJetsToLL_M50_HT1200to2500 xsec 0.236898 from Fall17_private_legacy_v1 different to xsec 0.186222 from Summer16_05Feb2018
* DYJetsToLL_M50_HT2500toInf xsec 0.00431853 from Autumn18_private_legacy_v1 different to xsec 0.00438495 from Summer16_05Feb2018
* DYJetsToLL_M50_HT2500toInf xsec 0.00422505 from Fall17_private_legacy_v1 different to xsec 0.00438495 from Summer16_05Feb2018

_Originally posted by @mzarucki in https://github.com/HephyAnalysisSW/Samples/pull/19#issuecomment-489203804_

**Comment by schoef** [comment]
I think these LO x-sec refer to different PDF sets and should stay as is?

**Comment by danbarto** [comment]
To clarify, the x-secs in the central (=not private) files are all copies from numbers from 2016. Those numbers were obtained using the GenXSecAnalyzer (MG, LO). Since PDFs, MG versions etc changed I updated the numbers for 2017 and 2018 (in case you have doubt about some numbers run the runXSecAnalyzer.py in Tools/scripts for any sample of your liking). I didn't yet pull the changes to the central files in order to not disturb anyones workflow.

**Comment by mzarucki** [comment]
Thanks for the commit here, updating the Fall17_14Dec2018: https://github.com/HephyAnalysisSW/Samples/commit/b9857fc24fd570f01346c3f9faff38fcdfd6ed87

For the DYJetsToLL_M50_HT70to100 in Summer16, should we update the value to what it is in the Twiki: https://twiki.cern.ch/twiki/bin/view/CMS/SummaryTable1G25ns#DY_Z (ie. 170.4 -> 169.9) or leave it as it is?

Cheers,
Mateusz

**Comment by danbarto** [comment]
Please go ahead and update it.

**Comment by mzarucki** [comment]
Done: https://github.com/HephyAnalysisSW/Samples/commit/a54b0f85c5c06f2ffcd87b90f255b9c05d962a7e
